services:
  php-apache:
    build: ./php
    container_name: php-apache
    volumes:
      - ./htdocs:/var/www/html
    restart: always
    ports:
      - "8000:80"

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MEMORY_LIMIT: 128M
      UPLOAD_LIMIT: 64M
    restart: always
    ports:
      - "8080:80"

volumes:
  db_data: {}
